name: Octo Organization CI

on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: ./.github/scripts/test.sh
        shell: bash
      - name: Run a one-line script
        run: echo Hello from Toto-testing Organization
