name: Octo Organization CI

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [ $default-branch ]

jobs:
  job_1:
    name: Upload File
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir folder
          echo "Hello World" > folder/file.txt
      - uses: actions/upload-artifact@v2
        with:
          name: file2
          path: folder/file.txt

  job_2:
    name: Download File
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: file2
          path: downloaded-folder/file.txt
      - run: cat downloaded-folder/file.txt
