name: Publish artifacts

on: push

jobs:
  build:
      name: toto
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            name: webpack artifacts
            path: public/
